# Generated by Django 4.2.4 on 2023-09-03 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название курса')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Превью')),
                ('description', models.TextField(verbose_name='Описание курса')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Стоимость курса')),
                ('currency', models.CharField(choices=[('usd', 'usd'), ('rub', 'rub')], default='rub', max_length=20, verbose_name='Валюта')),
                ('is_buy', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название урока')),
                ('description', models.TextField(verbose_name='Описание урока')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Превью')),
                ('link_to_video', models.CharField(max_length=255, verbose_name='Ссылка на видео')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Стоимость урока')),
                ('currency', models.CharField(choices=[('usd', 'usd'), ('rub', 'rub')], default='rub', max_length=20, verbose_name='Валюта')),
                ('is_buy', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now=True, verbose_name='Дата оплаты')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Сумма оплаты')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('money_transfer', 'денежный перевод')], default='money_transfer', verbose_name='Способ оплаты')),
                ('payment_currency', models.CharField(choices=[('usd', 'usd'), ('rub', 'rub')], default='rub', max_length=255, verbose_name='Валюта')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms_platform.course', verbose_name='Подписанный курс')),
            ],
        ),
    ]
