# Generated by Django 4.2.3 on 2023-08-08 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_platform', '0005_remove_subscription_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms_platform.course', verbose_name='Подписанный курс'),
        ),
    ]
